name: Continuous Integration and Deployment

on: 
  push: 
    branches:
      - master

jobs:
# name for job => "build"
  build: 
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v3
        with:
            dotnet-version: '6.0.x'
  
